# -*- coding: utf-8 -*-
"""Text Summarization Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ScqZayeABbiu_5YjtHsqNUy10E-v4P1n
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import pickle
import tensorflow as tf


# %matplotlib inline

def __init__(self):
        self.max_length_text = 80
        self.max_length_summary = 10
    
    def load_dataset(self,filename,nrows):
        data = pd.read_csv(filename + '.csv',nrows = nrows)
        
        return data
    
    def remove_columns(self,data):
        data = data.drop(['Id','ProductId','UserId','ProfileName', 'HelpfulnessNumerator','HelpfulnessDenominator', 'Score', 'Time'],1)
        
        return data

