# -*- coding: utf-8 -*-
"""Transformer-Multi-Label-Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/mahrub/transformer-multi-label-classification.f3db3f2a-f5b1-46fc-a474-7b288003422a.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260410/auto/storage/goog4_request%26X-Goog-Date%3D20260410T141010Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D55f6b545e6bbe2ef02149a916f16a07a0b4208447cba9fffb02cfb498f1d85b8bd91c668068f10cf49a277d8c2aee3d223dbb620922f6b526299f16e55621f8516e9af511b292180faec0ce6d84bf8aa666d35bb83e3e7af67b745fd9d275ae4fa361fcb5ef29114834e1cdeef5b8d70fcff36e4b1cb03910b19efc5d9709551e8ea9c8a71d4f95e8399fa1cf2f6d64e483a4f7c66f89e455a56e17021636d9977cfc54c2830bc92afdbb789c759bdc24c493c9156067cd3bb3a0ced4e9860a06862776e36cbc2531f94bedaa31695af8dfb0a715090bb35ad89a8f552ebd7486bd9ffda6b155579138574be7115fddd9a0862639eb5795d08fefcc5b6f1c4d8
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
shivanandmn_multilabel_classification_dataset_path = kagglehub.dataset_download('shivanandmn/multilabel-classification-dataset')

print('Data source import complete.')

"""# Part 1：data preprocessing

Transform the original multi-label classification dataset into a format suitable for the T5 model. Specifically, we will concatenate the titles and abstracts of the articles into a single text input and merge multiple labels marked as 1 into a semicolon-separated string of labels. Ultimately, this preprocessing step will generate a clear text-to-text format, preparing for the training of the T5 model.
"""

import pandas as pd

"""Prepare Data"""
input_csv = "train.csv"
data = pd.read_csv(input_csv)
print(len(data))
label_columns = data.columns[-6:]  # Extract the labels column
print(label_columns)

data['text'] = data['TITLE'] + " " + data['ABSTRACT']  # Prepare text
print(data['text'].head())

data['labels'] = data[label_columns].apply(lambda x: '; '.join(x.index[x == 1]), axis=1)
print(data['labels'])
# Displaying the updated dataset
preprocessed_data = data[['text', 'labels']]
print(preprocessed_data.head())

# Save as a new CSV file
output_path = "/kaggle/working/preprocessed_data.csv"
preprocessed_data.to_csv(output_path, index=False)

"""# Part 2：Model Training and Testing

This experiment still utilizes PyTorch and PyTorch Lightning as the experimental framework. Please refer to the official website for instructions on how to use PyTorch Lightning.

## Import the relevant packages.
"""

import pytorch_lightning as pl
from pytorch_lightning.loggers import TensorBoardLogger
from torch.utils.data import DataLoader
from pytorch_lightning.callbacks import ModelCheckpoint
from transformers import T5Tokenizer, T5ForConditionalGeneration, Trainer, TrainingArguments, AdamW
from datasets import load_dataset
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch.nn as nn
import torch
import csv
import datasets

"""## 2.1 Custom Batch Processing Function"""

def collate_fn(batch):
    """
    Custom Batch Processing Function
    """
    texts = [item['text'] for item in batch]
    labels = [item['labels'] for item in batch]
    # Encode text and labels using the tokenizer with a maximum length of 512.
    encoding = tokenizer(texts, padding=True, truncation=True, max_length=512, return_tensors="pt")
    # Encode labels using the target_tokenizer provided by the tokenizer.
    with tokenizer.as_target_tokenizer():
        labels_encoding = tokenizer(labels, padding=True, truncation=True, max_length=512, return_tensors="pt")
    # Replace the pad token in the labels with -100, as required by the T5 model.
    labels_encoding["input_ids"][labels_encoding["input_ids"] == tokenizer.pad_token_id] = -100

    return {
        'input_ids': encoding['input_ids'],
        'attention_mask': encoding['attention_mask'],
        'labels': labels_encoding['input_ids']
    }

"""## 2.2 Custom Dataset"""

class T5Dataset(Dataset):
    """Custom Dataset"""

    def __init__(self, dataset):
        self.dataset = dataset

    def __getitem__(self, idx):
        item = self.dataset[idx]
        return {
            'text': item['text'],
            'labels': item['labels']
        }

    def __len__(self):
        return len(self.dataset)

"""## 2.3 Custom LightningModule"""

class T5FineTuner(pl.LightningModule):
    """Custom LightningModule"""

    def __init__(self, train_dataset, val_dataset, test_dataset, learning_rate=2e-5):
        super(T5FineTuner, self).__init__()
        self.validation_loss = []
        self.model = T5ForConditionalGeneration.from_pretrained('t5-small')
        self.learning_rate = learning_rate  # Fine-tuning
        self.train_dataset = train_dataset
        self.val_dataset = val_dataset
        self.test_dataset = test_dataset
        self.prediction = []

    def forward(self, input_ids, attention_mask, labels=None):
        output = self.model(input_ids=input_ids,
                            attention_mask=attention_mask,
                            labels=labels)
        return output

    def configure_optimizers(self):
        return AdamW(self.model.parameters(), lr=self.learning_rate)

    def train_dataloader(self):
        train_loader = DataLoader(dataset=self.train_dataset, batch_size=batch_size, collate_fn=collate_fn,
                                  shuffle=True)
        return train_loader

    def val_dataloader(self):
        val_loader = DataLoader(dataset=self.val_dataset, batch_size=batch_size, collate_fn=collate_fn,
                                shuffle=False)
        return val_loader

    def test_dataloader(self):
        test_loader = DataLoader(dataset=self.test_dataset, batch_size=batch_size, collate_fn=collate_fn,
                                 shuffle=False)
        return test_loader

    def training_step(self, batch, batch_idx):
        input_ids = batch['input_ids']
        attention_mask = batch['attention_mask']
        labels = batch['labels']
        output = self(input_ids, attention_mask, labels)
        loss = output.loss
        self.log('train_loss', loss, prog_bar=True, logger=True, on_step=True, on_epoch=True)  # Output loss to console
        return loss

    def validation_step(self, batch, batch_idx):
        input_ids = batch['input_ids']
        attention_mask = batch['attention_mask']
        labels = batch['labels']
        output = self(input_ids, attention_mask, labels)
        loss = output.loss
        self.log('val_loss', loss, prog_bar=False, logger=True, on_step=True, on_epoch=True)
        return loss

    def test_step(self, batch, batch_idx):
        input_ids = batch['input_ids']
        attention_mask = batch['attention_mask']
        self.model.eval()
        # Generate output sequences
        generated_ids = self.model.generate(input_ids=input_ids, attention_mask=attention_mask)
        # Convert generated token IDs to text
        generated_texts = [tokenizer.decode(generated_id, skip_special_tokens=True, clean_up_tokenization_spaces=True)
                           for generated_id in generated_ids]
        # Return decoded text
        # print(generated_texts)
        self.prediction.extend(generated_texts)

"""## 2.4 Model Training and Testing"""

def test(model, fast_run):
    trainer = pl.Trainer(fast_dev_run=fast_run)
    trainer.test(model)
    test_result = model.prediction
    # print(type(test_result))
    for text in test_result[:10]:
        print(text)
    return test_result


def train(fast_run):
    # Add callback for the best model
    checkpoint_callback = ModelCheckpoint(
        monitor='val_loss',  # Monitoring object is 'val_loss'
        dirpath='/kaggle/working/T5FineTuner_checkpoints',  # Path to save the model
        filename='Models-{epoch:02d}-{val_loss:.2f}',  # Name for the best model
        save_top_k=1,  # Save only the best one
        mode='min'  # When the monitored metric is minimum
    )
    # Set the path for logging
    log_dir = "/kaggle/working/log"
    logger = TensorBoardLogger(save_dir=log_dir, name="T5FineTuner_logs")
    trainer = pl.Trainer(max_epochs=epochs, log_every_n_steps=10, accelerator='gpu', devices="auto", fast_dev_run=fast_run,
                         callbacks=[checkpoint_callback], logger=logger)
    model = T5FineTuner(train_dataset, valid_dataset, test_dataset, learning_rate)
    trainer.fit(model)
    return model

"""## 2.5 Save Prediction Results"""

def save_to_csv(test_dataset, predictions, filename="/kaggle/working/test_predictions.csv"):
    with open(filename, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow(['text', 'true_labels', 'pred_labels'])

        for item, pred_label in zip(test_dataset, predictions):
            text = item['text']
            true_labels = item['labels']
            writer.writerow([text, true_labels, pred_label])

"""## 2.6 Start Task"""

if __name__ == '__main__':
    # Define hyperparameters
    batch_size = 16
    epochs = 5
    learning_rate = 2e-5

    # data = load_dataset('csv', data_files={'train': '/kaggle/working/preprocessed_data.csv'})["train"]
    df_tmp = pd.read_csv('/kaggle/working/preprocessed_data.csv')
    data = datasets.Dataset.from_pandas(df_tmp)
    # Split dataset into training set and test+validation set
    train_testvalid = data.train_test_split(test_size=0.3, seed=42)
    # Split test+validation set into test set and validation set
    test_valid = train_testvalid['test'].train_test_split(test_size=0.5, seed=42)
    # Now we have training set, validation set, and test set
    train_dataset = train_testvalid['train']
    valid_dataset = test_valid['train']
    test_dataset = test_valid['test']
    # Print the size of each dataset
    print("Training set size:", len(train_dataset))
    print("Validation set size:", len(valid_dataset))
    print("Test set size:", len(test_dataset))
    # Prepare Dataset
    train_dataset = T5Dataset(train_dataset)
    valid_dataset = T5Dataset(valid_dataset)
    test_dataset = T5Dataset(test_dataset)
    # print(train_dataset.__len__())
    # print(train_dataset[0])

    # Initialize tokenizer
    tokenizer = T5Tokenizer.from_pretrained('t5-small')
    # Load DataLoader
    train_dataloader = DataLoader(dataset=train_dataset, batch_size=batch_size,
                                  collate_fn=collate_fn, shuffle=True, drop_last=True)
    # Check loading status
    for i, batch in enumerate(train_dataloader):
        print(f"Batch {i + 1}")
        print("Input IDs:", batch['input_ids'])
        print("Input IDs shape:", batch['input_ids'].shape)
        print("Attention Mask:", batch['attention_mask'])
        print("Attention Mask shape:", batch['attention_mask'].shape)
        print("Labels:", batch['labels'])
        print("\n")
        if i == 0:
            break

    fast_run = False
    model = train(fast_run)
#     model = T5FineTuner.load_from_checkpoint("Path",train_dataset=train_dataset, val_dataset=valid_dataset,test_dataset=test_dataset)
    pre_texts = test(model, fast_run)
    save_to_csv(test_dataset, pre_texts)

"""# Part 3：Model Evaluation"""

import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import numpy as np


def convert_labels(label_str):
    return label_str.split(';') if label_str else []


def clean_label(label):
    return label.strip()


# Read the provided CSV file
file_path = "/kaggle/working/test_predictions.csv"
data = pd.read_csv(file_path)
# print(data.head())

# Extract and convert the actual labels and predicted labels
true_labels = [convert_labels(label_str) for label_str in data['true_labels']]
pred_labels = [convert_labels(label_str) for label_str in data['pred_labels']]
# Recreate actual labels and predicted labels lists using cleaned labels
true_labels_cleaned = [list(map(clean_label, label_list)) for label_list in true_labels]
pred_labels_cleaned = [list(map(clean_label, label_list)) for label_list in pred_labels]


# Use MultiLabelBinarizer to one-hot encode the labels
mlb = MultiLabelBinarizer()
mlb.fit(true_labels_cleaned + pred_labels_cleaned)
y_true = mlb.transform(true_labels_cleaned)
y_pred = mlb.transform(pred_labels_cleaned)

print("Transformer(T5) Accuracy =", accuracy_score(y_true, y_pred))
print("Transformer(T5) Precision (micro-average) =", precision_score(y_true, y_pred, average='micro'))
print("Transformer(T5) Recall (micro-average) =", recall_score(y_true, y_pred, average='micro'))
print("Transformer(T5) F1 Score (micro-average) =", f1_score(y_true, y_pred, average='micro'))

print("\nAnother way to calculate accuracy:")
# Calculate accuracy for each column
column_accuracies = np.mean(y_true == y_pred, axis=0)
# Add column names to each column accuracy
column_accuracy_with_labels = list(zip(mlb.classes_, column_accuracies))
# Calculate the mean of column accuracies
mean_column_accuracy = np.mean(column_accuracies)

for acc in column_accuracy_with_labels:
    print(acc)
# print(column_accuracy_with_labels)
print("Average accuracy = ", mean_column_accuracy)

"""# Part 4：Experimental Results

This section summarizes and compares the results of various experiments conducted in the previous sections. We employed several algorithms to address the multi-label classification problem, including Binary Relevance (BR) combined with Random Forest, Classifier Chains (CC) combined with Random Forest, Label Powerset (LP) combined with Random Forest, LP combined with SVM, and the sequence generation method using the Transformer (T5) model.

By comparing the key performance metrics, including accuracy, micro-precision, micro-recall, and micro-F1 score, we found:

- The BR, CC, and LP methods based on Random Forest can achieve relatively good predictive performance.-
- Performance is further improved when LP is combined with SVM, especially in terms of recall and F1 score.
- Most notably, the Transformer (T5) model achieves the highest values in accuracy, recall and F1 score.

The specific numerical values are as follows:

| Algorithms       | Acc      | $Pre_{micro}$ | $Re_{micro}$ | $F1_{micro}$ |
| ---------------- | ---------- | ------------- | ------------ | ------------ |
| BR(RandomForest) | 0.4477     | **0.8038**    | 0.4978       | 0.6149       |
| CC(RandomForest) | 0.4787     | 0.8012        | 0.5277       | 0.6363       |
| LP(RandomForest) | 0.5349     | 0.7179        | 0.5889       | 0.6470       |
| LP(SVM)          | 0.5914     | 0.7368        | 0.7245       | 0.7306       |
| Transformer(T5)  | **0.6427** | 0.7994        | **0.7840**   | **0.7916**   |

From the results, we can conclude that the Transformer model demonstrates its powerful capability in handling complex multi-label classification tasks. This also indicates the wide-ranging potential and effectiveness of sequence-to-sequence models in the field of natural language processing (NLP).
"""